title: Zifeng Wang
name: Zifeng Wang
position: Ph.D. Candidate @ Georgia Tech
email: wstar266000@gmail.com
description: |
  I am a Ph.D. candidate at Georgia Institute of Technology in Material Science and Engineering (advisor: [Dr. Ting Zhu](https://www.me.gatech.edu/faculty/zhu-1)), 
  and an M.S. in Computational Science and Engineering. My research spans in **Materials foundation model**, **AI for science**.
  I have extensive industrial experience accross multiple areas, from AI/ML to manufacturing and material, where I had experience building end-to-end Vision-Language-Action (VLA) pipelines on real robotic platforms, including data collection, model training, deployment, and Sim2Real transfer.

  I am interested in Robotics learning area, seeking positions in **Robotics Learning, VLA/WAM Foundation Models, Deep Reinforcement Learning, and Autonomous Material Lab** area.
  
  


baseurl: ""
url: "https://zif-wang.github.io"
github_username: zif-wang
google_scholar: pFi6GegAAAAJ
linkedin_username: zifeng-wang-886a5b250

plugins:
  - jekyll-feed
  - jekyll-tailwindcss

permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      math: false
